spring:
  application:
    name: discodeit-dev
  server:
    port: 8081
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit_dev
    username: progres
    password: tmdcks1234
  jpa:
    hibernate:
      ddl-auto: update

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/dev-storage
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace