spring:
  application:
    name: discodeit-prod
  server:
    port: 8080
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://prod-db-host:5432/discodeit_prod
    username: progres
    password: tmdcks1234
  jpa:
    hibernate:
      ddl-auto: validate

discodeit:
  storage:
    type: local
    local:
      root-path: /var/discodeit/storage
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace