spring:
  application:
    name: discodeit
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tmdcks1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  logging:
    level:
      root: info
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    local:
      root-path: 'C:\Users\tmdck\IdeaProjects\pra\0-sprint-mission-s7-base\src\main\resources\storage'

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    version: 1.7.0
  java:
    version: 17
  spring:
    boot:
      version: 3.4.0
