spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    jwt:
      secret: ${SECURITY_JWT_SECRET}

# 추가 옵션 예시
server:
  port: 8080

logging:
  level:
    root: INFO